// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsGTPPobNtM1rA1gIpASva3e5tm3wImgQ',
    appId: '1:620194566707:web:a6f061ecc7fb0c67b68946',
    messagingSenderId: '620194566707',
    projectId: 'applearnenglish-6ac18',
    authDomain: 'applearnenglish-6ac18.firebaseapp.com',
    storageBucket: 'applearnenglish-6ac18.firebasestorage.app',
    measurementId: 'G-ZR5BZRS44B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAywr4HbmKAqHTFZdnIbVg2tmFJgHZYaiM',
    appId: '1:620194566707:android:fd3563c0a6d4504ab68946',
    messagingSenderId: '620194566707',
    projectId: 'applearnenglish-6ac18',
    storageBucket: 'applearnenglish-6ac18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLEhe4tVRFEHzjOiI22NY7upnX2Zt7KFE',
    appId: '1:620194566707:ios:96a0be50c3c75453b68946',
    messagingSenderId: '620194566707',
    projectId: 'applearnenglish-6ac18',
    storageBucket: 'applearnenglish-6ac18.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLEhe4tVRFEHzjOiI22NY7upnX2Zt7KFE',
    appId: '1:620194566707:ios:96a0be50c3c75453b68946',
    messagingSenderId: '620194566707',
    projectId: 'applearnenglish-6ac18',
    storageBucket: 'applearnenglish-6ac18.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsGTPPobNtM1rA1gIpASva3e5tm3wImgQ',
    appId: '1:620194566707:web:aa51e505641cac7bb68946',
    messagingSenderId: '620194566707',
    projectId: 'applearnenglish-6ac18',
    authDomain: 'applearnenglish-6ac18.firebaseapp.com',
    storageBucket: 'applearnenglish-6ac18.firebasestorage.app',
    measurementId: 'G-KEZ6ZBG1JH',
  );
}
